## For the European Paleopathology Association Conference 2024

c(
  "Is left-handed",
  "Is currently living in Canada",
  "Last name starts with A",
  "Has published on osteoarthritis",
  "Has used micro-CT scans in their research",
  "Is currently wearing osteo clothing",
  "Is currently wearing osteo jewellery",
  "Is wearing clogs",
  "Whose flight was delayed",
  "Has published in IJPP, IJO, AJBA, and BI",
  "Received their MA/MSc/MPhil in 2024",
  "Has an osteo-related desktop image",
  "Is going on all social programme activities",
  "Is from the Netherlands",
  "Speaks Dutch",
  "Knows the PPA motto",
  "Is on the Board of PPA",
  "Is giving a keynote lecture",
  "Is going to EAA after the EuroPPA",
  "Has a birthday in the same month as you",
  "Went to the previous EuroPPA meeting (Vilnius)",
  "Went to the previous PPA meeting (Los Angeles)",
  "Has written a book on paleopathology",
  "Has been a member of PPA for +20 years",
  "Has excavated in Africa",
  "Is from Italy",
  "Works with isotopes",
  "Works with aDNA",
  "Does not work for a university",
  "For whom this is their first international conference",
  "For whom this is their first conference",
  "Has been to Leiden before",
  "Has watched the entire Bones series",
  "Is giving a podium at the Leiden EuroPPAs",
  "Is giving a poster at the Leiden EuroPPAs",
  "Has a motorcycle",
  "Can speak three languages fluently",
  "Has published on sinusitis",
  "Has published on linear enamel hypoplasia",
  "Who knows the 3 pillars of the osteological paradox",
  "Went to the previous PAMinSA meeting (Bolivia)"
)
