# A nice icebreaker game for Open Science events
# Find someone who has practised Open Science and chat with them about it!

c(
  "Has published a preprint",
  "Has published data in a repository",
  "Has published code in a repository",
  "Has published a protocol (e.g., protocols.io)",
  "Has published a Data Article",
  "Has pre-registered a study",
  "Has published a registered report",
  "Has reproduced a study (same data, same method)",
  "Has replicated a study (new data, same method)",
  "Has done some form of science communication",
  "Has joined an Open Science Community",
  "Can describe the F in FAIR",
  "Can describe the A in FAIR",
  "Can describe the I in FAIR",
  "Can describe the R in FAIR",
  "Can name two types of persistent identifiers",
  "Can describe Green Open Access",
  "Can describe Diamond Open Access",
  "Can describe Gold Open Access",
  "Can describe Hybrid Open Access",
  "Can describe Bronze Open Access",
  "Can describe a registered report",
  "Can describe a pre-registration",
  "Has published in a Diamond Open Access journal",
  "Has published in a Gold Open Access journal",
  "Has created a Data Management Plan",
  "Has created a Software Management Plan",
  "Has participated in CODECHECK",
  "Has done an open peer-review (as the reviewer)",
  "Has done an open peer-review (as the reviewed)",
  "Has conducted/participated in a Citizen Science project",
  "Has published an Open Access Textbook",
  "Has openly published a course syllabus",
  "Has openly published course materials",
  "Has used an open source alternative to proprietary software",
  "Has an ORCID",
  "Has influenced Open Science policy (on any level)",
  "Has contributed to an open, community-driven project (The Turing Way, Carpentries, etc.)"
)
